# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginGeoSaude
                                 A QGIS plugin
 Plugin que permite carregar indicadores do GeoSaude no QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-17
        copyright            : (C) 2018 by UMinho
        email                : alunos@uminho
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PluginGeoSaude class from file PluginGeoSaude.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plugin_geosaude import PluginGeoSaude
    return PluginGeoSaude(iface)
