# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginGeoSaude
                                 A QGIS plugin
 Plugin que permite carregar indicadores do GeoSaude no QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-06-17
        git sha              : $Format:%H$
        copyright            : (C) 2018 by UMinho
        email                : alunos@uminho
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction
from qgis.core import QgsDataSourceUri, QgsVectorLayer, QgsProject
import psycopg2

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .plugin_geosaude_dialog import PluginGeoSaudeDialog
import os.path

class PluginGeoSaude:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'PluginGeoSaude_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = PluginGeoSaudeDialog()

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Plugin QGIS - GeoSaude')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'PluginGeoSaude')
        self.toolbar.setObjectName(u'PluginGeoSaude')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PluginGeoSaude', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/plugin_geosaude/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Plugin QGIS-GeoSaúde'),
            callback=self.run,
            parent=self.iface.mainWindow())


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Plugin QGIS - GeoSaude'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar


    def run(self):
        connect = psycopg2.connect("dbname=twlzfg_enzffb host=db.qgiscloud.com user=twlzfg_enzffb password=bd1e4c96")
        cursor = connect.cursor()
        query = "select nomemapa from mapas order by nomemapa asc"
        cursor.execute(query)
        layer_list = []
        layers = cursor.fetchall()
        for layer in layers:
            layer_list.append(str(layer[0]))
        self.dlg.comboBox.clear()
        self.dlg.comboBox.addItems(layer_list)
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        if result:
            uri = QgsDataSourceUri()
            # set host name, port, database name, username and password
            uri.setConnection("db.qgiscloud.com", "5432", "twlzfg_enzffb", "twlzfg_enzffb", "bd1e4c96")
            # set database schema, table name, geometry column
            tabela = str(self.dlg.comboBox.currentText())
            cursor = connect.cursor()
            cursor.execute("select idmapa, camada from mapas where nomemapa = (%s)", (tabela,))
            colunas = cursor.fetchall()
            for coluna in colunas:
                idmapa = str(coluna[0])
                camada = str(coluna[1])
            uri.setDataSource("public", idmapa, "geom")
            vlayer = QgsVectorLayer(uri.uri(), camada, "postgres")
            QgsProject.instance().addMapLayer(vlayer, True)
            cursor.close()
            connect.close()